    name: CI

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build
          run: echo Building...

      test:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/checkout@v2
        - name: Test
          run: echo Testing...

      deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
        - uses: actions/checkout@v2
        - name: Deploy
          run: echo Deploying...
