name: CI avec Artefacts

on: [push]

jobs:
  job1_produire_artefact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Créer un fichier artefact
      run: echo "Contenu de mon artefact !" > mon_artefact.txt

    - name: Uploader l'artefact
      uses: actions/upload-artifact@v4
      with:
        name: resultat-job1
        path: mon_artefact.txt

  job2_consommer_artefact:
    runs-on: ubuntu-latest
    needs: job1_produire_artefact
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Télécharger l'artefact
      uses: actions/download-artifact@v4
      with:
        name: resultat-job1
        # path: ./destination_optionnelle # par défaut à la racine du workspace

    - name: Utiliser l'artefact
      run: cat mon_artefact.txt

