    name: CI

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Use a secret
          run: echo ${{ secrets.MY_SECRET }}
